### PR TITLE
Feat: Add customer_usage

### LINKED ISSUE #6: Get customer usage metric
## Context
 Different nois-proxy contracts deployed on different chains request the beacon from Nois, we want to keep track of the usage of these proxies. So we want to see dashboards that track how much every proxy uses.
The way we currently do it is to manually query the usage sum per proxy for the current block height with this python script: https://gist.github.com/kaisbaccour/bb9451a46086b62f33b77da9d8563961
The output of such script is as follows:

```sh
> python3 customers_usage.py |jq -r '.mainnet'
{
  "channel-11": {
    "requested_beacons": 3640,
    "proxy": "juno1avjq06m3l03pl2k8ecvpdhkzrld8s3x48qvhp8merhfjh753vvdskqqs74"
  },
  "channel-2": {
    "requested_beacons": 31983,
    "proxy": "juno1qr84ktm57q5t02u04ddk5r8s79axdzglad6tfdd9g2xgt4hkh6jsgeq9x2"
  },
  "channel-20": {
    "requested_beacons": 83,
    "proxy": "inj1w9g3sk7lk8k0pdtctygupt6f3te7x4thvzz57a"
  },
  "channel-22": {
    "requested_beacons": 753,
    "proxy": "archway10f3aasgsnpv84ymjyld50jayc4ecu267sdpjamauwm8nvxlzex9qj4dkwr"
  },
  "channel-35": {
    "requested_beacons": 159,
    "proxy": "aura1r3zgdsn3dcze07a4r60rxxx7ppvkxfshn9np0pwtkgarrld0786s72jtjt"
  },
  "channel-38": {
    "requested_beacons": 10979,
    "proxy": "stars1mw5y55f53mnara7g3pn2pylxl8dpauscyn83c68442hz9nwktzrq8tjzyf"
  },
  "channel-41": {
    "requested_beacons": 2,
    "proxy": "osmo1tvzr8ur0ynjhqftxpkl4qwel8ly7erhy6cu6ks426xmzf92vk6eqfp9wcl"
  }
}
```

This is not ideal because we cannot see the evolution in time and it is not centrally available on a dashboarding tool.
## Implementation:
We want provide prometheus metrics that show this usage so that we can display the dashboard on grafana.
to achieve this we would need to query the customers for the nois-gateway contract on Nois chain
nois gateway contract address: 
mainnet: nois1acyc05v6fgcdgj88nmz2t40aex9nlnptqpwp5hf8hwg7rhce9uuqgqz5wp
testnet: nois1xwde9rzqk5u36fke0r9ddmtwvh43n4fv53c5vc462wz8xlnqjhls6d90xc

Querying the customers would give a result like this
```sh
> noisd query  wasm contract-state smart nois1acyc05v6fgcdgj88nmz2t40aex9nlnptqpwp5hf8hwg7rhce9uuqgqz5wp  '{"customers":{}}'   --chain-id=nois-1  --node=https://rpc.cosmos.directory:443/nois | yq
data:
  customers:
    - channel_id: channel-11
      payment: nois1re6jdd097wtc0nz9g63amxh2hejfzuqc49ukz8yslaq2pkkr32dqcmk0pn
      requested_beacons: 3640
    - channel_id: channel-2
      payment: nois1k7a00gmhj450qa83xq2v3rlmfcp8nj8t2wc653maq9p5csv4q5jq5pwfm0
      requested_beacons: 31998
    - channel_id: channel-20
      payment: nois1yt80qt66qkd7d07sv0ff2qw7pazdd2cuhwhg9e0jg9ckt46k7nlqvhffm0
      requested_beacons: 83
    - channel_id: channel-22
      payment: nois1rf3qhpwrs6zy0hun9qua56har9jrfau97c006czg7mjmhq7c09uqa2l7rg
      requested_beacons: 753
    - channel_id: channel-35
      payment: nois17ptlmlqwl4y7rmf34ytlw5gmv0j8s0795j4rxx65e6px00zd4zes32g7kz
      requested_beacons: 159
    - channel_id: channel-38
      payment: nois18ne5rx6vsufdgsst39l22fu3jc3vy4q4k623lyrcpj7wwdp0xg0sh2w332
      requested_beacons: 11010
    - channel_id: channel-41
      payment: nois16uwwdg6f9rem5k3gzlpf4uvk0m8htvwry9mtkczxdx8yqd4a8d5s9pe5uh
      requested_beacons: 2
```

Then we need to extract what those channels mean (i.e what proxy refers to what channel), for that we query the Nois chain for the ibc corresponding ibc channels, from there we  extract the counterparty.port_id which looks like wasm.stars1mw5y55f53mnara7g3pn2pylxl8dpauscyn83c68442hz9nwktzrq8tjzyf

The final goal is to expose the metrics with a label proxy_address and the metric the number of requested beacons

### PR DESCRIPTION
**Pull request by hoangdv2429**
This PR will add the usage metrix and close #6 . The details mapping still need to be add.

### CODE REVIEW

**Comment by kaisbaccour** [comment]
> @kaisbaccour Can you have a look at this PR sir 🙌 Thank you!

This is very hard to read because it's mostly linting changes so all the code is changing. and it's hard to see what changed. Can we do the linting separately ?

**Comment by hoangdv2429** [comment]
is it better sir 🙌 @kaisbaccour I revert the linting.

**Comment by kaisbaccour** [comment]
I'm gonna merge to dev to be able to test it

**Comment by kaisbaccour** [comment]
Screenshot 2024-01-18 at 12 26 17
When launching the server I only see the balances

**Comment by hoangdv2429** [comment]
Screenshot 2024-01-18 at 18 29 19
I'm querying the port 3000 though, is that suppose to be on 18101 ?

**Comment by kaisbaccour** [comment]
no

> Screenshot 2024-01-18 at 18 29 19 I'm querying the port 3000 though, is that suppose to be on 18101 ?

No I'm forwarding  ports from docker but okay maybe I'm doing something wrong, will try and check more

**Comment by kaisbaccour** [comment]
Great looks like a good step already now we need both contracts testnet and mainnet.
And as you said the matching with the customer chain address is needed

**Comment by kaisbaccour** [comment]
Screenshot 2024-01-18 at 15 08 15
Okay this step looks good

**Comment by kaisbaccour** [comment]
Okay I added the description for the channels and pushed to the dev branch so you can rebase. Now what is reamaining is pretty much getting the addresses that correspond to these channesls. from the ibc port-id

**Pull request merged**
